/* automatically generated by rust-bindgen 0.72.1 */

// Generated from the C codec headers by CMake. Do not edit.
#![expect(dead_code, non_camel_case_types)]

pub const KF_CODEC_OK: KfCodecResult = 0;
pub const KF_CODEC_END: KfCodecResult = 1;
pub const KF_CODEC_INVALID: KfCodecResult = 2;
pub const KF_CODEC_OUTPUT_FULL: KfCodecResult = 3;
pub type KfCodecResult = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfTimInfo {
    pub mode: u32,
    pub width: u32,
    pub height: u32,
    pub encoded_bytes: u32,
    pub image_x: i32,
    pub image_y: i32,
    pub palette_x: i32,
    pub palette_y: i32,
}
pub const KF_AUDIO_PROGRAM_COUNT: _bindgen_ty_1 = 128;
pub const KF_AUDIO_TONE_COUNT: _bindgen_ty_1 = 16;
pub const KF_AUDIO_SAMPLE_COUNT: _bindgen_ty_1 = 256;
pub type _bindgen_ty_1 = ::core::ffi::c_uint;
pub const KF_AUDIO_ADPCM_BLOCK_BYTES: _bindgen_ty_2 = 16;
pub const KF_AUDIO_ADPCM_BLOCK_FRAMES: _bindgen_ty_2 = 28;
pub type _bindgen_ty_2 = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioEnvelope {
    pub attack_shift: u8,
    pub attack_step: u8,
    pub decay_shift: u8,
    pub sustain_shift: u8,
    pub sustain_step: u8,
    pub release_shift: u8,
    pub sustain_level: u16,
    pub attack_exponential: u8,
    pub sustain_exponential: u8,
    pub sustain_decreasing: u8,
    pub release_exponential: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioTone {
    pub priority: u8,
    pub reverb: u8,
    pub volume: u8,
    pub pan: u8,
    pub center_note: u8,
    pub center_shift: u8,
    pub minimum_note: u8,
    pub maximum_note: u8,
    pub vibrato_width: u8,
    pub vibrato_time: u8,
    pub portamento_width: u8,
    pub portamento_time: u8,
    pub bend_down: u8,
    pub bend_up: u8,
    pub sample_index: u16,
    pub envelope: KfAudioEnvelope,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioProgram {
    pub tone_count: u8,
    pub volume: u8,
    pub pan: u8,
    pub priority: u8,
    pub tones: [KfAudioTone; 16usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioSampleRange {
    pub offset: u32,
    pub size: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioBankData {
    pub volume: u8,
    pub pan: u8,
    pub sample_count: u16,
    pub programs: [KfAudioProgram; 128usize],
    pub samples: [KfAudioSampleRange; 256usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioSampleInfo {
    pub frames: u32,
    pub loop_begin: u32,
    pub loop_end: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioPredictor {
    pub previous: i32,
    pub older: i32,
}
pub const KF_MUSIC_NOTE_OFF: KfMusicEventKind = 0;
pub const KF_MUSIC_NOTE_ON: KfMusicEventKind = 1;
pub const KF_MUSIC_VOLUME: KfMusicEventKind = 2;
pub const KF_MUSIC_PROGRAM: KfMusicEventKind = 3;
pub const KF_MUSIC_PITCH_BEND: KfMusicEventKind = 4;
pub const KF_MUSIC_TEMPO: KfMusicEventKind = 5;
pub const KF_MUSIC_END: KfMusicEventKind = 6;
pub type KfMusicEventKind = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfMusicEvent {
    pub delta: u32,
    pub kind: KfMusicEventKind,
    pub value: u32,
    pub channel: u8,
    pub note: u8,
    pub velocity: u8,
    pub reserved: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfMusicInfo {
    pub resolution: u32,
    pub tempo: u32,
    pub event_count: u32,
}
