/* automatically generated by rust-bindgen 0.72.1 */

// Generated from the C codec headers by CMake. Do not edit.
#![expect(dead_code, non_camel_case_types)]

pub const KF_CODEC_OK: KfCodecResult = 0;
pub const KF_CODEC_END: KfCodecResult = 1;
pub const KF_CODEC_INVALID: KfCodecResult = 2;
pub const KF_CODEC_OUTPUT_FULL: KfCodecResult = 3;
pub type KfCodecResult = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfTimInfo {
    pub mode: u32,
    pub width: u32,
    pub height: u32,
    pub encoded_bytes: u32,
    pub image_x: i32,
    pub image_y: i32,
    pub palette_x: i32,
    pub palette_y: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAssetInfo {
    pub encoded_bytes: u32,
    pub tmd_offset: u32,
    pub clip_count: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAnimationClipData {
    pub first_keyframe: usize,
    pub keyframe_count: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAnimationKeyframe {
    pub reverse: u16,
    pub duration: u16,
    pub rest_morph: u16,
    pub first_morph: usize,
    pub morph_count: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAnimationMorph {
    pub base_vertex: u32,
    pub first_delta: usize,
    pub delta_count: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAnimationDelta {
    pub x: i16,
    pub y: i16,
    pub z: i16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAnimationSizes {
    pub clips: usize,
    pub keyframes: usize,
    pub morphs: usize,
    pub indices: usize,
    pub deltas: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAnimationOutput {
    pub clips: *mut KfAnimationClipData,
    pub keyframes: *mut KfAnimationKeyframe,
    pub morphs: *mut KfAnimationMorph,
    pub indices: *mut u16,
    pub deltas: *mut KfAnimationDelta,
    pub capacity: KfAnimationSizes,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfPlacementLimits {
    pub map_side: u32,
    pub definitions: u32,
    pub tile_size: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfActorPlacementData {
    pub slot_state: u8,
    pub definition_id: u8,
    pub near_square_culling: u8,
    pub heading_quadrant: u8,
    pub tile_z: u8,
    pub tile_x: u8,
    pub spawn_chance: u8,
    pub death_drop_object_id: u8,
    pub local_z: i16,
    pub local_x: i16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfObjectPlacementData {
    pub object_id: u8,
    pub tile_z: u8,
    pub tile_x: u8,
    pub yaw: u16,
    pub local_z: i16,
    pub local_x: i16,
    pub local_y: i16,
    pub link: [u32; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfEventPlacementData {
    pub state: u8,
    pub character_id: u8,
    pub model_index: u8,
    pub cell_z: u8,
    pub cell_x: u8,
    pub dialogue_pages: [u8; 5usize],
    pub dialogue_stage_limit: u8,
    pub unknown_0b: u8,
    pub unknown_0c: u8,
    pub behavior: u8,
    pub position_z_offset: i16,
    pub position_x_offset: i16,
    pub initial_rotation: u16,
    pub radius: u16,
}
pub const KF_AUDIO_PROGRAM_COUNT: _bindgen_ty_1 = 128;
pub const KF_AUDIO_TONE_COUNT: _bindgen_ty_1 = 16;
pub const KF_AUDIO_SAMPLE_COUNT: _bindgen_ty_1 = 256;
pub type _bindgen_ty_1 = ::core::ffi::c_uint;
pub const KF_AUDIO_ADPCM_BLOCK_BYTES: _bindgen_ty_2 = 16;
pub const KF_AUDIO_ADPCM_BLOCK_FRAMES: _bindgen_ty_2 = 28;
pub type _bindgen_ty_2 = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioEnvelope {
    pub attack_shift: u8,
    pub attack_step: u8,
    pub decay_shift: u8,
    pub sustain_shift: u8,
    pub sustain_step: u8,
    pub release_shift: u8,
    pub sustain_level: u16,
    pub attack_exponential: u8,
    pub sustain_exponential: u8,
    pub sustain_decreasing: u8,
    pub release_exponential: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioTone {
    pub priority: u8,
    pub reverb: u8,
    pub volume: u8,
    pub pan: u8,
    pub center_note: u8,
    pub center_shift: u8,
    pub minimum_note: u8,
    pub maximum_note: u8,
    pub vibrato_width: u8,
    pub vibrato_time: u8,
    pub portamento_width: u8,
    pub portamento_time: u8,
    pub bend_down: u8,
    pub bend_up: u8,
    pub sample_index: u16,
    pub envelope: KfAudioEnvelope,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioProgram {
    pub tone_count: u8,
    pub volume: u8,
    pub pan: u8,
    pub priority: u8,
    pub tones: [KfAudioTone; 16usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioSampleRange {
    pub offset: u32,
    pub size: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioBankData {
    pub volume: u8,
    pub pan: u8,
    pub sample_count: u16,
    pub programs: [KfAudioProgram; 128usize],
    pub samples: [KfAudioSampleRange; 256usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioSampleInfo {
    pub frames: u32,
    pub loop_begin: u32,
    pub loop_end: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfAudioPredictor {
    pub previous: i32,
    pub older: i32,
}
pub const KF_MUSIC_NOTE_OFF: KfMusicEventKind = 0;
pub const KF_MUSIC_NOTE_ON: KfMusicEventKind = 1;
pub const KF_MUSIC_VOLUME: KfMusicEventKind = 2;
pub const KF_MUSIC_PROGRAM: KfMusicEventKind = 3;
pub const KF_MUSIC_PITCH_BEND: KfMusicEventKind = 4;
pub const KF_MUSIC_TEMPO: KfMusicEventKind = 5;
pub const KF_MUSIC_END: KfMusicEventKind = 6;
pub type KfMusicEventKind = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfMusicEvent {
    pub delta: u32,
    pub kind: KfMusicEventKind,
    pub value: u32,
    pub channel: u8,
    pub note: u8,
    pub velocity: u8,
    pub reserved: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KfMusicInfo {
    pub resolution: u32,
    pub tempo: u32,
    pub event_count: u32,
}
