#pragma once
// System and portable interfaces live outside the original modules' namespaces.
#include <cstddef>
#include <cstdint>
#include <bit>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <algorithm>
#include <cmath>
#include <limits>
#include <type_traits>
#include <kf/lib/types.h>
#include <kf/lib/fixed_math.hpp>
#include <kf/lib/random.hpp>
#include <kf/audio/sound.hpp>
#include <kf/platform/files.hpp>
#include <kf/platform/saves.hpp>
#include <kf/platform/host.hpp>
#include <kf/platform/module_state.hpp>
#include <kf/platform/input.hpp>
#include <kf/lib/codec.h>
#include <kf/renderer/renderer.hpp>
#include <kf/renderer/lighting.hpp>
#include <kf/renderer/projection.hpp>
#include <kf/lib/geometry_types.h>

// Shared game-library types and operations have one identity across phases.
#include <kf/lib/math.h>
#include <kf/lib/memory.h>
#include <kf/lib/resources.h>
#include <kf/lib/resource_file.h>
#include <kf/lib/debug.h>
#include <kf/lib/audio.h>
#include <kf/lib/map_types.h>
#include <kf/lib/item_types.h>
#include <kf/lib/camera_path.h>
#include <kf/lib/render_types.h>
#include <kf/lib/tmd.h>
#include <kf/lib/graphics.h>
#include <kf/lib/render_face.h>
