#ifndef KF_MAGIC_H
#define KF_MAGIC_H

#include <kf/lib/audio.h>

enum {
    KF_MAGIC_PLAYER_COUNT = 9,
    KF_MAGIC_RECORD_COUNT = 24,
    KF_MAGIC_TABLE_WORD_COUNT = 120,
    KF_MAGIC_SOUND_COUNT = 2,
    KF_MAGIC_DAMAGE_COMPONENT_COUNT = 4
};

typedef u8 KfEffectKind; enum {
    KF_MAGIC_HEALING = 0,
    KF_MAGIC_DISPOISON = 1,
    KF_MAGIC_RESIST_FIRE = 2,
    KF_MAGIC_BLESS = 3,
    KF_MAGIC_LIGHTNING_BOLT = 4,
    KF_MAGIC_FIRE_BALL = 5,
    KF_MAGIC_FIRE_WALL = 6,
    KF_MAGIC_WIND_CUTTER = 7,
    KF_MAGIC_LIGHT_NEEDLE = 8,
    KF_MAGIC_NONE = 0xff,
    KF_EFFECT_KIND_ACTOR_SPAWNER = 9,
    KF_EFFECT_KIND_SCATTER_PROJECTILE = 10,
    KF_EFFECT_KIND_DARKNESS_PROJECTILE = 11,
    KF_EFFECT_KIND_CURSE_PROJECTILE = 12,
    KF_EFFECT_KIND_EMERGING_PROJECTILE = 13,
    KF_EFFECT_KIND_MAP_EMITTER_PROJECTILE = 14,
    KF_EFFECT_KIND_SWINGING_HAZARD_SHORT = 15,
    KF_EFFECT_KIND_SWINGING_HAZARD_LONG = 16,
    KF_EFFECT_KIND_ORBITING_PROJECTILE = 17,
    KF_EFFECT_KIND_RADIAL_BLAST = 18,
    KF_EFFECT_KIND_GROUND_TRAIL = 19,
    KF_EFFECT_KIND_HOMING_PROJECTILE = 20,
    KF_EFFECT_KIND_WARP_SHIMMER = 21,
    KF_EFFECT_KIND_PHYSICAL_PROJECTILE = 22,
    KF_EFFECT_KIND_LIGHTNING_IMPACT = 32,
    KF_EFFECT_KIND_LIGHTNING_RADIAL_BLAST = 33,
    KF_EFFECT_KIND_GROUND_BRANCH_VISUAL = 34,
    KF_EFFECT_KIND_MOONLIGHT_PROJECTILE = 36,
    KF_EFFECT_KIND_LIGHTNING_BOLT_ALTERNATE = 23,
    KF_EFFECT_KIND_HOMING_PROJECTILE_ALTERNATE = 24,
    KF_EFFECT_KIND_LIGHTNING_IMPACT_ALTERNATE = 41,
    KF_EFFECT_KIND_LIGHTNING_RADIAL_BLAST_ALTERNATE = 42,
    KF_EFFECT_KIND_RADIAL_BLAST_ALTERNATE = 44,
    KF_EFFECT_KIND_MAP_SWITCH = 48,
    KF_EFFECT_KIND_FLOOR_DEFORMATION = 52
};

typedef u8 KfMagicLearningState; enum {
    KF_MAGIC_UNLEARNED = 0,
    KF_MAGIC_LEARNED = 1
};

typedef struct KfMagicRecord {
    KfMagicLearningState learned;
    u8 charge_rate;
    SoundRef sounds[KF_MAGIC_SOUND_COUNT];
    u16 damage_components[KF_MAGIC_DAMAGE_COMPONENT_COUNT];
    u16 mp_cost;
    u8 unknown_12[0x02];
} KfMagicRecord;

typedef struct KfMagicTable {
    KfMagicRecord entries[KF_MAGIC_RECORD_COUNT];
} KfMagicTable;

extern void magic_load_records(const KfMagicTable *table);
extern void magic_cast(void);

#endif
