"""Render and replace the generated README match-status block."""

from __future__ import annotations

import fcntl
import os
from pathlib import Path

from scripts.kf.paths import BUILD, REPO


README = REPO / "README.md"
START = "<!-- match-score:start -->"
END = "<!-- match-score:end -->"


def _percent(numerator: int, denominator: int) -> float:
    return 100.0 * numerator / denominator if denominator else 0.0


def render_block(document: dict) -> str:
    """Render the strict-100% per-image status snapshot as compact Markdown."""
    total = document["total"]
    rows = []
    for key in ("psx", "game", "open"):
        summary = document["images"][key]
        exact = int(summary["exact_functions"])
        eligible = int(summary["eligible_functions"])
        rows.append(
            f"| `{key.upper()}.EXE` | {exact:,} / {eligible:,} "
            f"({_percent(exact, eligible):.2f}%) | "
            f"{int(summary['manifested_functions']):,} | "
            f"{float(summary['fuzzy_overall_percent']):.2f}% |"
        )
    exact = int(total["exact_functions"])
    eligible = int(total["eligible_functions"])
    rows.append(
        f"| **Total** | **{exact:,} / {eligible:,} "
        f"({_percent(exact, eligible):.2f}%)** | "
        f"**{int(total['manifested_functions']):,}** | "
        f"**{float(total['fuzzy_overall_percent']):.2f}%** |"
    )
    return "\n".join((
        START,
        "## Match status",
        "",
        "_Auto-generated by `kf check` (the final `kf build` edge) and "
        "`kf bank`; do not hand-edit._",
        "",
        f"**Overall: {exact:,} / {eligible:,} functions exact "
        f"({_percent(exact, eligible):.2f}%) &middot; "
        f"{float(total['coverage_percent']):.2f}% exact-code coverage &middot; "
        f"{float(total['fuzzy_overall_percent']):.2f}% fuzzy.**",
        "",
        "| Image | Functions exact | Started | Fuzzy (overall) |",
        "| :---- | --------------: | ------: | --------------: |",
        *rows,
        "",
        "_Exact requires 100%. The denominator excludes identified Sony/Psy-Q "
        "library functions._",
        END,
    ))


def write_block(block: str, path: Path = README) -> bool:
    """Replace only the marked block, inserting it after the intro if absent."""
    text = path.read_text(encoding="utf-8")
    if START in text and END in text:
        before = text[:text.index(START)]
        after = text[text.index(END) + len(END):]
        content = before + block + after
    else:
        heading = text.index("\n## ") if "\n## " in text else len(text)
        content = text[:heading].rstrip() + "\n\n" + block + "\n" + text[heading:]
    if content == text:
        return False
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        temporary.write_text(content, encoding="utf-8")
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)
    return True


def refresh() -> bool:
    """Serialize full-tree snapshot + README replacement across image checks."""
    lock = BUILD / "gen" / "readme.lock"
    lock.parent.mkdir(parents=True, exist_ok=True)
    with lock.open("a+") as stream:
        fcntl.flock(stream, fcntl.LOCK_EX)
        from scripts.kf.progress import snapshot

        document, _failures = snapshot()
        return write_block(render_block(document))
