# Keep each original translation unit intact, with independent module linkage.
# Wrappers contain includes, not generated copies of gameplay implementations.
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/build.json")
function(kf_original_module target module_index)
  file(READ "${PROJECT_SOURCE_DIR}/build.json" inventory)
  string(JSON module_name GET "${inventory}" modules ${module_index} name)
  string(JSON count LENGTH "${inventory}" modules ${module_index} sources)
  math(EXPR last "${count} - 1")
  set(wrappers)
  foreach(index RANGE ${last})
    string(JSON source GET "${inventory}" modules ${module_index} sources ${index})
    set(wrapper "${CMAKE_CURRENT_BINARY_DIR}/original/${module_name}/${index}.cpp")
    file(GENERATE OUTPUT "${wrapper}" CONTENT
      "#include <kf/platform/prelude.hpp>\nnamespace kf::${module_name} {\n#include \"${PROJECT_SOURCE_DIR}/${source}\"\n}\n")
    list(APPEND wrappers "${wrapper}")
  endforeach()
  set(entry "${CMAKE_CURRENT_BINARY_DIR}/original/${module_name}/entry.cpp")
  file(GENERATE OUTPUT "${entry}" CONTENT
    "#include <kf/platform/prelude.hpp>\nnamespace kf::${module_name} {\n#include \"${PROJECT_SOURCE_DIR}/src/platform/${module_name}_entry.inc\"\n}\n")
  add_library(${target} OBJECT ${wrappers} "${entry}")
  target_include_directories(${target} PRIVATE "${PROJECT_SOURCE_DIR}/include")
  target_compile_options(${target} PRIVATE -Wall -Wextra -fwrapv -fno-strict-aliasing)
  target_compile_definitions(${target} PRIVATE KF_PORTABLE)
  if(module_name STREQUAL "opening")
    target_compile_definitions(${target} PRIVATE KF_OPEN)
  endif()
endfunction()
kf_original_module(kf_game 0)
kf_original_module(kf_opening 1)
