# Phase namespaces separate scene policy; common library sources compile once.
# Wrappers contain includes, not generated copies of gameplay implementations.
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/build.json")
function(kf_original_module target module_index)
  file(READ "${PROJECT_SOURCE_DIR}/build.json" inventory)
  string(JSON module_name GET "${inventory}" modules ${module_index} name)
  string(JSON count LENGTH "${inventory}" modules ${module_index} sources)
  math(EXPR last "${count} - 1")
  set(wrappers)
  foreach(index RANGE ${last})
    string(JSON source GET "${inventory}" modules ${module_index} sources ${index})
    set(wrapper "${CMAKE_CURRENT_BINARY_DIR}/original/${module_name}/${index}.cpp")
    file(GENERATE OUTPUT "${wrapper}" CONTENT
      "#include <kf/platform/prelude.hpp>\nnamespace kf::${module_name} {\n#include \"${PROJECT_SOURCE_DIR}/${source}\"\n}\n")
    list(APPEND wrappers "${wrapper}")
  endforeach()
  add_library(${target} OBJECT ${wrappers})
  target_include_directories(${target} PRIVATE "${PROJECT_SOURCE_DIR}/include")
  target_compile_options(${target} PRIVATE -Wall -Wextra -fwrapv -fno-strict-aliasing)
  target_compile_definitions(${target} PRIVATE KF_PORTABLE)
endfunction()
kf_original_module(kf_game 0)
kf_original_module(kf_opening 1)

file(READ "${PROJECT_SOURCE_DIR}/build.json" inventory)
string(JSON shared_count LENGTH "${inventory}" shared_sources)
math(EXPR shared_last "${shared_count} - 1")
set(shared_sources)
foreach(index RANGE ${shared_last})
  string(JSON source GET "${inventory}" shared_sources ${index})
  list(APPEND shared_sources "${PROJECT_SOURCE_DIR}/${source}")
endforeach()
add_library(kf_common OBJECT ${shared_sources})
target_include_directories(kf_common PRIVATE "${PROJECT_SOURCE_DIR}/include")
target_compile_options(kf_common PRIVATE -Wall -Wextra -fwrapv -fno-strict-aliasing)
target_compile_definitions(kf_common PRIVATE KF_PORTABLE)
