#pragma once
#include <kf/lib/types.h>

enum {
    KF_MAP_OBJECT_DEFINITION_COUNT = 160,
    KF_MAP_OBJECT_DEFINITION_WORD_COUNT = 320,
    KF_MAP_RESOURCE_PATH_BYTES = 12,
    KF_MAP_OBJECT_CAPACITY = 190,
    KF_MAP_CONTAINER_ITEM_COUNT = 4,
    KF_MAP_OBJECT_EFFECT_FIRST = 160,
    KF_MAP_EVENT_CAPACITY = 8
};

enum class KfMapObjectOperation : u8 {
    KF_MAP_OBJECT_OP_HINGED_DOOR = 0,
    KF_MAP_OBJECT_OP_HINGED_DOOR_PARTNER = 1,
    KF_MAP_OBJECT_OP_LIFT_DOOR = 2,
    KF_MAP_OBJECT_OP_03 = 3,
    KF_MAP_OBJECT_OP_HINGED_CONTAINER = 8,
    KF_MAP_OBJECT_OP_ITEM_CONTAINER = 9,
    KF_MAP_OBJECT_OP_COPY_REGION = 10,
    KF_MAP_OBJECT_OP_RESTORE_POINT = 11,
    KF_MAP_OBJECT_OP_REVEAL_MAP_PIECE = 12,
    KF_MAP_OBJECT_OP_SCREEN_IMAGE = 13,
    KF_MAP_OBJECT_OP_SAVE_POINT = 14,
    KF_MAP_OBJECT_OP_ITEM_PICKUP = 64,
    KF_MAP_OBJECT_OP_GOLD_PICKUP = 65,
    KF_MAP_OBJECT_OP_PROJECTILE_EMITTER = 80,
    KF_MAP_OBJECT_OP_RELEASE_ORBIT_OR_SHORT_SWING = 81,
    KF_MAP_OBJECT_OP_RELEASE_LONG_SWING = 82,
    KF_MAP_OBJECT_OP_EFFECT_SWITCH = 83,
    KF_MAP_OBJECT_OP_FALL_AND_TIP = 96,
    KF_MAP_OBJECT_OP_FALL_AND_SPIN = 97,
    KF_MAP_OBJECT_OP_BOUNCE = 98,
    KF_MAP_OBJECT_OP_NONE = 255,
    KF_MAP_OBJECT_OP_HINGED_DOOR_END = 2,
    KF_MAP_OBJECT_OP_LINK_TRIGGER_END = 8,
    KF_MAP_OBJECT_OP_LINK_CLEAR_LAST = 8
}; using enum KfMapObjectOperation;

typedef struct KfMapObjectDefinition {
    KfMapObjectOperation behavior_type;
    u8 unknown_01;
    u16 collision_radius;
    u16 interaction_radius;
    u8 unknown_06[2];
} KfMapObjectDefinition;

typedef struct KfMapObjectDefinitionTable {
    KfMapObjectDefinition entries[KF_MAP_OBJECT_DEFINITION_COUNT];
} KfMapObjectDefinitionTable;
