#ifndef KF_NOTIFY_TYPES_H
#define KF_NOTIFY_TYPES_H

#include <kf/lib/types.h>
#include <kf/lib/enum.h>

/* Message cells in the Japanese retail notification atlas. */
KF_ENUM_BEGIN(KfNotificationId, u8)
    KF_NOTIFICATION_LEVEL_UP = 0,
    KF_NOTIFICATION_MAGIC_LEARNED = 1,
    KF_NOTIFICATION_LOCKED = 2,
    KF_NOTIFICATION_SEALED = 3,
    KF_NOTIFICATION_KEY_DOES_NOT_FIT = 4,
    KF_NOTIFICATION_NOTHING_THERE = 5,
    KF_NOTIFICATION_NOTHING_INSIDE = 6,
    KF_NOTIFICATION_DEAD = 7,
    KF_NOTIFICATION_BROKEN_SWORD = 8,
    KF_NOTIFICATION_OLD_BONES = 9,
    KF_NOTIFICATION_SCHOLAR_BONES = 10,
    KF_NOTIFICATION_HANS_CORPSE = 11,
    KF_NOTIFICATION_PITFALL = 12,
    KF_NOTIFICATION_HEALING_SPRING = 13,
    KF_NOTIFICATION_REINHARDT_II = 14,
    KF_NOTIFICATION_INVISIBLE_WALL = 15,
    KF_NOTIFICATION_CANNOT_CARRY_MORE = 16,
    KF_NOTIFICATION_HIDDEN_DOOR = 17,
    KF_NOTIFICATION_NOTHING_HAPPENS = 18,
    KF_NOTIFICATION_GOLD = 19,
    KF_NOTIFICATION_RAITO_FAMILY_GRAVE = 20,
    KF_NOTIFICATION_GRAVESTONE = 21,
    KF_NOTIFICATION_BROKEN_SHOVEL = 22,
    KF_NOTIFICATION_POISON_HOLE = 23,
    KF_NOTIFICATION_BOTTOMLESS_PIT = 24,
    KF_NOTIFICATION_WIND_SEAL = 25,
    KF_NOTIFICATION_FIRE_SEAL = 26,
    KF_NOTIFICATION_EARTH_SEAL = 27,
    KF_NOTIFICATION_WATER_SEAL = 28,
    KF_NOTIFICATION_RECOVERED = 29,
    KF_NOTIFICATION_PHYSICAL_POWER_INCREASED = 30,
    KF_NOTIFICATION_MAGIC_POWER_INCREASED = 31,
    KF_NOTIFICATION_NONE = 0xff
KF_ENUM_END(KfNotificationId)

/* Keep the legacy variadic argument word-sized and the modern enum domain. */
typedef KF_ENUM_PROMOTED(KfNotificationId) KfNotificationArgument;

KF_ENUM_BEGIN(KfNotificationPhase, u8)
    KF_NOTIFICATION_IDLE = 0,
    KF_NOTIFICATION_HOLD = 2,
    KF_NOTIFICATION_ROTATE_OUT = 3
KF_ENUM_END(KfNotificationPhase)

#endif
